### ISSUE TITLE
Command only insert data and not create migrations

### ISSUE THREAD

**Issue by RomanNebesnuyGC** [TheDragonCode/migrate-db#11]
- Migrade DB Version: 1.2.0
- PHP Version: 7.4.22
- Laravel/Lumen Framework Version: 8.54.0
- Database Driver & Version: PostgreSQL 13.2 and MariaDB 10.5.11

### Description:
Command doesn't create migration for table. In code it only transfer data from one database to another. For example in my case from PostgreSQL to MariaDB. But MariaDB has empty DB and I thought it must create migration and then insert all data from PostgreSQL, but this command only insert data and that's all. It doesn't make sense..

### Execution result:

<details>
    <summary>Show result</summary>

    // paste result here

</details>

**Comment by andrey-helldar** [comment]
The `php artisan db:migrate` command makes a call to perform migrations (see [here](https://github.com/andrey-helldar/migrate-db/blob/main/src/Console/Migrate.php#L72-L78)) and then transfers the data.

Check your target connection settings.
Also, if execution does not throw an error, then it is being executed.

**Comment by andrey-helldar** [comment]
The `php artisan db:migrate` command makes a call to perform migrations (see [here](https://github.com/andrey-helldar/migrate-db/blob/main/src/Console/Migrate.php#L72-L78)) and then transfers the data.

Check your target connection settings.
Also, if execution does not throw an error, then it is being executed.

What error did you get?

**Comment by RomanNebesnuyGC** [comment]
Sorry may be I don't understand something. But command that you give a link only run "php artisan migrate" for connection. But I mean I have PostgreSQL database (without migrations), only DB. And I thought this library will create migrations by itself and then also will move data to another database.

**Comment by andrey-helldar** [comment]
Yes, it should.

Can you write in detail which command you run? Together with the parameters.

Also check which database the data should be transferred to.

Internal [tests](https://github.com/andrey-helldar/migrate-db/runs/3348738425?check_suite_focus=true) for migrating data from PostgreSQL to MySQL run smoothly.
